const linux = () => {

    const linuxInfo = "Linux  – rodzina uniksopodobnych systemów operacyjnych opartych na jądrze Linux. Linux jest jednym z przykładów wolnego i otwartego oprogramowania (FLOSS): jego kod źródłowy może być dowolnie wykorzystywany, modyfikowany i rozpowszechniany. Od kwietnia 2017 roku Android (a tym samym Linux) oficjalnie jest najpopularniejszym systemem operacyjnym na świecie.Pierwsza wersja jądra Linux została udostępniona publicznie 17 września 1991 dla architektury komputera PC, wykorzystującego mikroprocesor o architekturze IA-32. Do jądra dołączono narzędzia systemowe zwane też „Development Kit” oraz biblioteki z projektu GNU, aby otrzymać nadający się do użytku system operacyjny. Z tego powodu powstała też alternatywna nazwa kompletnego systemu: GNU/Linux. Obecnie jest on udostępniany w formie licznych dystrybucji Linuksa, które składają się z jądra (niekiedy zmodyfikowanego w stosunku do oficjalnej wersji) i zestawu pakietów oprogramowania dobranego do różnorodnych wymagań. Dystrybucje zawierają głównie oprogramowanie na licencjach FLOSS, jednak najczęściej zawierają też lub pozwalają na łatwe doinstalowanie pewnej liczby programów na licencjach własnościowych.Jednym z zastosowań Linuksa są środowiska serwerowe, dla których komercyjne wsparcie oferują również duże firmy komputerowe jak IBM, Oracle, Dell, Microsoft, Hewlett-Packard, Red Hat i Novell. Linux działa na szerokiej gamie sprzętu komputerowego, wliczając komputery biurkowe, superkomputery i systemy wbudowane, takie jak telefony komórkowe, routery oraz telewizory (np. LG, Samsung).";
    const debian = "Debian – projekt wolnej dystrybucji systemu operacyjnego GNU/Linux oraz GNU/kFreeBSD realizowany przez ochotników na całym świecie. Wewnątrz Debiana istnieją również projekty, mające na celu stworzenie dystrybucji systemu GNU/Hurd, inne odmiany BSD, a nawet dystrybucji wolnego oprogramowania na platformę Windows.Debian cieszy się opinią stabilnego systemu o wysokiej jakości i łatwego do aktualizacji[potrzebny przypis]. Ze względu na dbałość o jakość i bezpieczeństwo dystrybucji, nowe wersje stabilne pojawiają się stosunkowo rzadko, często dochodzi też do opóźnień w ich wydawaniu. Powstanie Debiana ogłosił 16 sierpnia 1993 r. na grupie comp.os.linux.development Ian Murdock, wówczas student uniwersytetu Purdue. Napisał on Manifest Debiana, w którym apelował o stworzenie otwartej dystrybucji w duchu Linuksa i GNU. Nazwa „Debian” jest zbitką imion Murdocka i jego dziewczyny (obecnie byłej żony) Debry. Dystrybucja ta została zbudowana na podstawie SLS. Wśród założeń Debiana było między innymi to, że będzie zawierał on najbardziej aktualne wersje oprogramowania.";

    const arch = "Arch Linux – dystrybucja GNU/Linuksa stworzona przez Judda Vineta. Stawia ona sobie za cel łatwość konfiguracji i użytkowania systemu operacyjnego, a także dostępność znacznej ilości aktualnego oprogramowania, którym można w prosty i wygodny sposób zarządzać. Łatwość ta nie jest jednak osiągana przez dużą ilość graficznych konfiguratorów, a poprzez przemyślnie rozmieszczone i zaprojektowane pliki konfiguracyjne, skrypty i programy. Dlatego też Arch Linux, mimo swojej prostoty, może nie być odpowiednim systemem dla osób niemających wcześniej styczności z GNU/Linuksem ani dla tych, dla których używanie konsoli oraz edycja plików tekstowych w celu zmiany ustawień mogą sprawiać problemy.Inspiracją dla Judda Vineta była inna, wcześniejsza dystrybucja GNU/Linuksa – CRUX. Arch jest oparty na systemie pakietów binarnych kompilowanych dla architektur i686 oraz x86_64 zarządzanych przez specjalnie do tego zadania stworzony program o nazwie pacman. Umożliwia on instalację, aktualizację oraz usuwanie pakietów. Pakiety mogą być także budowane ze źródeł przy pomocy ABS (Arch Linux Build System) – systemu podobnego do portów FreeBSD. Umożliwia on proste i szybkie budowanie pakietów i włączanie ich do systemu. Instalacja przebiega w trybie tekstowym, a użytkownik może dokonać konfiguracji systemu edytując odpowiednie pliki.Dostępne jest wydanie dedykowane architekturze ARM, działające m.in. na platformie Raspberry Pi. Arch stanowi podstawę dla wielu dystrybucji pochodnych, m.in. Manjaro.";

    const red = "Red Hat, Inc. – amerykańskie przedsiębiorstwo informatyczne założone przez Marca Ewinga w 1993 roku i zajmujące się tworzeniem i dystrybucją otwartego oprogramowania dla przedsiębiorstw. Znane z wydawania dystrybucji GNU/Linuksa – Red Hat Linux – a następnie jej pochodnych: komercyjnego Red Hat Enterprise Linux oraz wspierania społecznościowej dystrybucji Fedory. Główna siedziba przedsiębiorstwa znajduje się w mieście Raleigh w amerykańskim stanie Karolina Północna.Przedsiębiorstwo jest zaangażowane w ruch otwartego oprogramowania, promując open source w filozofii firmy W marcu 1993 roku w Connecticut Kanadyjczyk Robert Young założył ACC Corporation Inc., w tym samym roku Marc Ewing założył firmę Red Hat. 3 listopada 1994 roku Ewing wydał wersję 1.0 swojej dystrybucji Red Hat Linux. W 1995 roku Young przejął firmę Ewinga, po czym połączył ją z ACC Corp, zmienił nazwę tej ostatniej nad Red Hat i objął kierownictwo nad całością.W 1999 roku Red Hat stał się spółką publiczną: w pierwszej ofercie publicznej na giełdzie NASDAQ 11 sierpnia 1999 roku dla 6 milionów zaoferowanych akcji ustalono cenę 14 dolarów amerykańskich za sztukę; zaś w pierwszych godzinach debiutu tego samego dnia ich cena wzrosła prawie trzykrotnie, mimo wykazywanych strat. 15 listopada tego samego roku Red Hat podpisał umowę przejęcia innej spółki zajmującej się rozwojem otwartego oprogramowania, Cygnus Solutions, w transakcji wycenianej na 674 mln dolarów, przejęcie zostało zakończone w styczniu 2000 roku.22 lutego 2000 roku Red Hat przedstawił na rynku zapowiedź nowej linii biznesowej: Red Hat Linux Enterprise Edition.28 października 2018 roku amerykańska korporacja IBM ogłosiła zamiar przejęcia Red Hat Inc. za 33,4 mld dolarów amerykańskich (190 dolarów za akcję, 63% drożej od kursu z piątku";

    const android = "Android – system operacyjny z jądrem Linux dla urządzeń mobilnych takich jak telefony komórkowe, smartfony, tablety (tablety PC) i netbooki. W 2013 roku był najpopularniejszym systemem mobilnym na świecie. Wspomniane jądro oraz niektóre inne komponenty, które zaadaptowano do Androida opublikowane są na licencji GNU GPL. Android nie zawiera natomiast kodu pochodzącego z projektu GNU. Cecha ta odróżnia Androida od wielu innych istniejących obecnie dystrybucji Linuksa. Początkowo był rozwijany przez firmę Android Inc. (kupioną później przez Google), następnie przeszedł pod skrzydła Open Handset AllianceAndroid zrzesza przy sobie dużą społeczność deweloperów piszących aplikacje, które poszerzają funkcjonalność urządzeń. W sierpniu 2014 było dla tego systemu dostępnych ponad 1,3 miliona aplikacji w Google Play (wcześniej Android Market).Według danych serwisu StatCounter z kwietnia 2017 roku Android miał największe udziały na rynku systemów operacyjnych[.";

    document.querySelector('#linux__text').innerHTML = linuxInfo;
    document.querySelector('#debian__text').innerHTML = debian;
    document.querySelector('#arch__text').innerHTML = arch;
    document.querySelector('#android__text').innerHTML = android;
    document.querySelector('#redhat__text').innerHTML = red;

}
linux();