const unix = () =>{
    const unixInfo ="Unix Time-Sharing System (pisane również jako UNIX, choć nie jest to skrót – nazwa „UNIX” jest kalamburem określenia Multics, który był wzorem dla Uniksa) – system operacyjny rozwijany od 1969 r. w Bell Labs (UNIX System Laboratories, USL) przez Dennisa Ritchie i Kena Thompsona. W latach 70. i 80. zdobył bardzo dużą popularność, co zaowocowało powstaniem wielu odmian i implementacji. Część z nich, w szczególności GNU/Linux oraz macOS, jest w użyciu do dziś. UNIX jest zarejestrowanym znakiem towarowym The Open Group.Unix miał duży wkład w rozwój systemów operacyjnych, wprowadzając wiele koncepcji będących w powszechnym użyciu do dziś. Do najbardziej znaczących należy upowszechnienie hierarchicznego systemu plików oraz reprezentacji niemal wszystkich składników systemu jako plików (również urządzeń peryferyjnych). Twórcy systemu zastosowali podczas jego tworzenia wiele nowatorskich rozwiązań oraz założeń projektowych. Narzędzia systemowe zostały zaprojektowane zgodnie z regułą KISS mówiącą, że programy powinny być proste i realizować dobrze jedną rzecz.";
    const historia = "System UNIX (Uniplexed Information and Computing System) powstał pod koniec lat 60. Jego twórcami byli Ken Thompson i Dennis Ritchie, programiści z działu badawczego Bell Labs. System ten z założenia miał być prosty w obsłudze oraz napisany w języku o wysokim poziomie. Początkowo był to język B, ale w roku 1973 system UNIX został przepisany na C. Z czasem drogi twórców Unixa się rozeszły. W ten sposób doszło do powstania dwóch wersji systemu. Pierwsza powstała na Uniwersytecie Kalifornijskim w Berkeley i została nazwana BSD (Berkeley Software Distribution), natomiast druga “System V” była kontynuowana w AT&T. Wersje te zaczęły ze sobą konkurować w latach 80. Z czasem AT&T sprzedało licencje na swojego Unixa wielu innym producentom sprzętu. Spowodowało to powstania komercyjnych wersji takich jak np. Solaris firmy Sun Microsystems. Komercjalizacja systemu UNIX nie spodobała się Richardowi Stallmanowi z Massachusetts Institute of Technology (MIT). Zaczął on więc pracę nad całkowicie darmową wersją Unixa - GNU (GNU's Not Unix). Głównymi założeniami GNU były: pełen dostęp do źródeł, możliwość ich kopiowania oraz rozpowszechniania. Do lat 90 jedynym brakującym elementem było jądro. W roku 1991 udało się je stworzyć Linusowi Torvaldsowi – studentowi informatyki z Uniwersytetu Helsińskiego. Jądro to zostało nazwane „Linux”. Tak powstał system GNU/Linux potocznie zwany Linuksem. Pierwsza wersja Linuksa mogła obsługiwać dyski oraz mały system plików. Nie miała jednak jeszcze zaimplementowanej obsługi napędu dyskietek. Wolny dostęp do źródła sprawił, że powstało kilka wydań różniących się rodzajem dołączonych programów oraz sposobem przygotowania systemu. Najpopularniejszymi dystrybucjami w latach 90-tych były Debian, Red Hat oraz Slackware. Szybki rozwój systemu sprawia, że jest on coraz bardziej powszechny. W ostatnich latach popularność Linuksa wzrosła do tego stopnia, że stał się on największą konkurencją dla systemu Microsoft Windows." ;

    const zastosowanie = "W porównaniu z Windows Unix jest bardzo stabilnym i oferującym duże możliwości w zakresie komend systemem operacyjnym. Jest dość trudny w obsłudze, a ze względu na możliwości i przeznaczenie bardziej narażony na ataki ze strony hackerów niż Windows. Obsługa, praca i administracja systemu klasy Unix wymaga od użytkownika przynajmniej dobrej znajomości systemu, podczas gdy obsługa Windows – co najwyżej podstawowej. Z tego względu Unix powinien być przede wszystkim stosowany w środowiskach o dużym obciążeniu systemu, wymagających stabilnej pracy i (UWAGA!) wysokiego poziomu bezpieczeństwa. Nie pozostaje to w sprzeczności z narażeniem na ataki hackerów – po prostu solidny administrator potrafi zabezpieczyć serwer tak, aby praktycznie (ale nie teoretycznie) nie można było się na niego włamać. Unix raczej nie nadaje się do zastosowań domowych ze względu na bardzo ograniczone oprogramowanie, które może zaoferować potencjalnemu użytkownikowi. Fani Unixa instalują go często jako drugi system operacyjny, jednak instalacja systemu klasy Unix bez stałego łącza do Internetu po prostu nie ma sensu. Przez bardzo długi czas systemy operacyjne oparte na UNIX-ach były całkowicie niedostępne dla zwykłych użytkowników, ze względu na swoje horrendalne jak na tamte czasy ceny komputerów, które spełniałyby ich wymagania sprzętowe. Nowa era systemów UNIX-owych nastała w momencie wejścia na rynek i popularyzacji komputerów osobistych. Kiedy w laboratoriach firmy Intel został wyprodukowany procesor 386, który bardzo szybko został hitem na rynku komputerów osobistych, pojawił się problem z dostępem do taniego systemu operacyjnego.Unix jest środkiem grzybobójczym w formie granul do sporządzania zawiesiny wodnej o działaniu wgłębnym, do stosowania zapobiegawczego i interwencyjnego w ochronie zbóż ozimych przed chorobami grzybowymi.";

    const polecenia ="cat – wypisywanie i łączenie plików <br> chgrp – zmiana grupy pliku <br> chmod – zmiana praw dostępu do pliku <br> chown – zmiana właściciela/grupy pliku <br> chattr – zmiana konkretnych atrybutów pliku <br> cd – zmiana bieżącego katalogu, użyty bez argumentów powraca do katalogu domowego <br> cp – kopiowanie plików <br> df – wypisywanie wolnej przestrzeni zamontowanych systemów plików du – wyświetla ilość miejsca zajmowanego przez pliki/katalogi file – ustalanie typu danych zawartych w pliku find – przeszukiwanie systemu plików getfacl – odczytanie prawa dostępu z list ACL ln – tworzenie dowiązań twardych i symbolicznych (patrz niżej) ls – listowanie zawartości katalogu lsof – wyświetlanie listy otwartych plików, oraz używających ich programów mkdir – tworzenie katalogów mkfifo – tworzenie nazwanych potoków mv – przenoszenie/zmiana nazwy pliku <br> pwd – wydruk aktualnego katalogu rcp – transfer plików na zdalny host <br> rm – usuwanie plików i katalogów. rmdir – usuwanie katalogów <br> scp – transfer plików bezpiecznym kanałem, SSH, na zdalny host setfacl – ustawienie prawa dostępu list ACL split – dzielenie pliku na kawałki rsync – synchronizacja plików, ewentualnie również bezpiecznym kanałem, SSH. touch – zamiana daty ostatniej modyfikacji, lub dostępu do pliku bądź utworzenie pustego pliku umask – wyświetla aktualną i umożliwia zmianę maski uprawnień dla tworzonych plików unlink – wywołanie systemowe, usuwanie pliku lub katalogu";

    document.querySelector('#historia__text').innerHTML=historia;
    document.querySelector('#zastosowanie__text').innerHTML=zastosowanie;
    document.querySelector('#unix__text').innerHTML=unixInfo;
    document.querySelector('#polecenia__text').innerHTML=polecenia;




}

unix();



